name: myelin-meta-analysis
channels:
  - conda-forge
dependencies:
  - r-base=3.6.1
  - r-metafor
  - python=3.7
  - pip
  - pip:
    - numpy == 1.18.4
    - pandas == 0.25.3
    - plotly == 4.8.1
    - rpy2 == 3.3.4
    - xlrd == 1.2.0
